### ISSUE TITLE
Базовые замены

### ISSUE THREAD

**Issue by hippogamesunity** [hippogamesunity/LinguoApp#1]
Требуется реализовать список базовых замен следующих символов:
A a - А а 
Ą a - Ѫ ѫ 
B b - Б б 
C c - Ц ц 
D d - Д д 
E e - Э э 
Ę ę - Ѧ ѧ 
F f - Ф ф 
G g - Г г 
H h - Ґ ґ 
I i - И и 
J j - Й й 
K k - К к 
Ł ł - Л л 
M m - М м 
N n - Н н 
O o - О о 
Ó ó - Ó ó 
P p - П п 
R r - Р р 
S s - С с 
T t - Т т 
U u - У у 
W w - В в 
Y y - Ы ы 
Z z - З з 
Ż ż - Ж ж
Sz sz - Ш ш 
Cz cz - Ч ч 
Ch ch - Х х 
Szcz szcz - Щ щ

**Comment by hippogamesunity** [comment]
Задачу можно закрыть? закрой если да

**Comment by Lagodny69** [comment]
можно закрыть
