### ISSUE TITLE
Словарные слова

### ISSUE THREAD

**Issue by Lagodny69** [hippogamesunity/LinguoApp#10]
Нужно иметь возможность записывать ряд словарных слов, которые не поддаются правилам, несколько таких слов я уже записывал ранее например слово klawiatura, но после твоих изменений с римскими цифрами они больше не переводятся

**Comment by hippogamesunity** [comment]
Привет! Очень размыто описано. Требуется уточнить:
1. Шаги воспроизведения
2. Ожидаемый результат
3. Реальный результат

**Comment by hippogamesunity** [comment]
Это баг или задача? Если задача про словарь, но те вижу проблемы заносить такие слова в начало общих словарей.
