### ISSUE TITLE
Баги

### ISSUE THREAD

**Issue by Lagodny69** [hippogamesunity/LinguoApp#11]
V не транслируется как В (возможно это связанно с латинскими цифрами, мы когда-то делали для польского их трансляцию)
E не транслируется как е (после согласных оно так должны)
Остаётся вопрос с w

**Comment by Lagodny69** [comment]
баг с е решён

**Comment by Lagodny69** [comment]
Я залил в гит первую версию перевода чешская кириллица-латиница, нужно пофиксить и залить на сайт

**Comment by hippogamesunity** [comment]
что я должен пофиксить?

**Comment by Lagodny69** [comment]
Закрываю тему в виду ненадобности
