### ISSUE TITLE
Локализация

### ISSUE THREAD

**Issue by Lagodny69** [hippogamesunity/LinguoApp#13]
На сайте нужно переименовать 
1. Select language: на Выбрать язык:
2. Polish на Polski/Польски
3. Czesz na Český/Чески́
4. В разделе польского языка переименовать Latin на Łacina, а Cyrillic na Цырылица.
4.1.  В разделе польского языка переименовать кнопки Translate на Przetłumacz и Претлумачь. 
5. В разделе чешского языка переименовать Latin на Latina Цырилице.
5.1. В разделе польского языка переименовать кнопки Translate на Přeložit и Преложит

**Comment by hippogamesunity** [comment]
Там еще заголовок есть

**Comment by Lagodny69** [comment]
@hippogamesunity Какой заголовок?

**Comment by Lagodny69** [comment]
@hippogamesunity я переименовал часть надписей, однако как изменить надписи в списке я не знаю, а также надписи не переключаются при выборе чешского.

**Comment by hippogamesunity** [comment]
у окна кажется

4 июня 2018 г., 22:23 пользователь Lagodny69 <notifications@github.com>
написал:

**Comment by Lagodny69** [comment]
Нужно адаптировать сайт под два языка (а в будущем под большее количество)

**Comment by hippogamesunity** [comment]
готово

**Comment by hippogamesunity** [comment]
в трансляторе CZ сейчас ошибка - дублируется ключ в словаре.

**Comment by Lagodny69** [comment]
Какой ключ дублируется?

**Comment by Lagodny69** [comment]
Пофиксил

**Comment by hippogamesunity** [comment]
Не знаю, исключение при переводе. Проверь словарь.

2018-06-05 18:16 GMT+03:00 Lagodny69 <notifications@github.com>:
