### ISSUE TITLE
Мелкие вопросы дизайна

### ISSUE THREAD

**Issue by Lagodny69** [hippogamesunity/LinguoApp#15]
Это негорящий вопрос, так совсем. Хотелось бы выбор языка засунуть куда-то в угол или в варианте списка (если это возможно) а также чтобы при смене языка менялся язык других кладок (вкладок информация и связь)

**Comment by hippogamesunity** [comment]
Пиши конкретно что перевести и варианты перевода.

**Comment by Lagodny69** [comment]
Польская версия сайта:
Название кнопок на верху Транслятор - Информацъя - Контакт 
Текст во вкладке информация: 
Тэн тлумач зостал створёны през мѩдзысловяньскѫ групѧ "Володари" в цэлю усправненя комуникацъї мѩдзы Поляками а ужитковниками цырылицы (на базе ѩзыка староцэркевнословяньскего). Опера сѩ на клясычнэй ортографии старословяньскей (не вплыва то на читане). Скопюй тэкст, артыкул люб вядомосьть до тлумача, а настѧпне ужий го до власных потреб. Есьли зауважиш блѫд тэхничны люб маш пропозыцъѩ, напиш до нас (патрь дял информацыйны).
Текст на вкладке Контакт
Георгий Милованов - глóвны володар
Вспарте:Svaznoyjedi@mail.ru

**Comment by Lagodny69** [comment]
Чешская версия сайта:
Название кнопок на верху Прекладател - Информаце - Контакт
Текст во вкладке информация:
Тенто прекладател был вытворен скупиноу мезивойводŏ "Володари", абы се злепшила комуникаце мези Полáки а цырілски́ми уживатели (заложенá на старослованске́м слованске́м языце). Е заложен на класицке́ старослованске́ правописне́ ґрафице (неовливнюе чтени́). Зкопи́руйте текст, члáнек небо зпрáву прекладатели а поте́ ей поужийте подле свы́х потреб. Покуд се обеви́ техницкá хыба небо мáте нѣяки́ нáврг, напище нáм (виз чáст с информацеми).
Текст на вкладке Контакт
Георгий Милованов - главни́ володар
Подпора:Svaznoyjedi@mail.ru

**Comment by hippogamesunity** [comment]
готово

**Comment by Lagodny69** [comment]
Выглядит просто супер!!!!!
