### ISSUE TITLE
Транслитерация йотированных 

### ISSUE THREAD

**Issue by Lagodny69** [hippogamesunity/LinguoApp#2]
Транслятор должен уметь записывать йотированные гласные.
Они будут встречаться в трёх видах: 
1. В начале слова или в середине после гласных записанные через йот "j" jechać - ехать , już - юж, jabłko - яблко, Józef - Éзэф, joż - ёж.
2. В середине слова после согласных записанные через йот "j" должны разделяться твёрдым знаком wjechać - въехать, racja - рацъя, Rosja - Росъя.
3. В середине слова после согласных записанные через дифтонг с "i" (ia ią ie ię io ió iu) w mieście - 
в месте, wiatr - вятр, siema - сема, ziemia - земя, się - сѩ, cię - тѩ.

**Comment by hippogamesunity** [comment]
Так же требуется более четкая формулировка. При программировании не может быть никаких неточностей или неясностей.
0. Нужен список всех согласных и всех гласных. Можно одной строкой без пробелов и запятых. Так же нужен список вообще всех букв польского алфавита (маленькие и большие).
1. Как компьютер должен определить и различать термины "начало слова" или "середина слова"? Нужны совершенно четкие критерии. Например: произвести замены je>е, ju>ю, ja>я, jo>ё (+ заглавные) в случае, если перед перед j стоит небуквенный символ или гласная буква (использовать алфавит и список гласных из пункта 0), например в качестве небуквенного символа могут быть пробел, разрыв строки или знак пунктуации.
2. Если перед j стоит согласная (пункт 0), то произвести замену j>ъ, так получается?
3. Произвести замены ie>е и др. (указать полный список), если перед j стоит согласная (пункт 0).

Кроме того, прошу указывать полный список замен, чтобы я их копировал. В пункте 3 нет полного списка. Я хочу копировать символы из задачи, чтобы не было вольностей при печати (е русская и e английская например, это два разных символа, не различимых глазом).

**Comment by Lagodny69** [comment]
польский алфавит полный:
A, a 
Ą, ą 
B, b  
C, c 
Ch, ch 
Cz, cz   
Ć, ć 
D, d  
Dź, dź 
E, e
Ę, ę 
F, f 
G, g  
H, h  
I, i  
J, j 
K, k  
L, l   
Ł, ł 
M, m   
N, n   
Ń, ń  
O, o 
Ó, ó 
P, p    
R, r   
Rz, rz   
S, s  
Sz, sz   
Ś, ś 
T, t   
U, u 
W, w   
Y, y   
Z, z   
Ź, ź 
Ż, ż

**Comment by Lagodny69** [comment]
Гласные звуки:
A, a
Ą, ą
E, e
Ę, ę
O, o
Ó, ó
U, u
Y, y 
I, i

**Comment by Lagodny69** [comment]
Согласные звуки
B, b  
C, c
Ch, ch 
Cz, cz  
Ć, ć
D, d  
Dź, dź
F, f
G, g  
H, h  
K, k  
L, l  
Ł, ł
M, m  
N, n  
Ń, ń  
P, p  
R, r  
Rz, rz  
S, s  
Sz, sz  
Ś, ś
T, t  
W, w  
Z, z  
Ź, ź
Ż, ż

**Comment by Lagodny69** [comment]
правило записи: 
одна из йотированных гласный пишется в случае
записи буквы йот (j) + гласная, в начале слове или после гласной (тогда пишется одна из соответствующих йотированных)
записи буквы (i) + гласная (тогда пишется одна из соответствующих йотированных).
записи буквы йот (j) + гласная, после согласной (тогда пишется ъ + одна из соответствующих йотированных) 
список соответствий:
Ja/ia - Я я
Je/ie - Е е
Jo/io - Ё ё
Jó/jó - É é
Ju/iu - Ю ю
Ji/ji - Ї ї
Ją/ią - Ѭ  ѭ
Ję/ię - Ѩ ѩ
выше записан (слева) польские согласные + йот (j) и (справа) кириллические аналоги.

**Comment by hippogamesunity** [comment]
Сделал итерацию замены RegexReplace. Обозначения:
^ - начинается с указанной строки
[C] - гласная (от Consonant), для регулярного выражения происходит замена на [AaĄąEeĘęOoÓóUuYyIi]
[^C] - не гласная, для регулярного выражения происходит замена на [^AaĄąEeĘęOoÓóUuYyIi]. Не путать символ домика с началом строки! Внутри квадратных скобок он выполняет роль отрицания.
[V] - согласная (от Vowel), для регулярного выражения происходит замена на [BbCcChchCzczĆćDdDźdźFfGgHhKkLlŁłMmNnŃńPpRrRzrzSsSzszŚśTtWwZzŹźŻż]
[^V] - не согласная (любой символ, кроме согласных - знак пунктуации или гласная)

Примеры:
{ "^Ja", "Я" } - заменить в начале строки
{ "[C]Ja", "Я" } - заменить после гласной, при этом оставить гласную
{ "[V]Ia", "я" } - заменить после согласной, при этом оставить согласную

Более подробно можно почитать про синтаксис регулярных выражений тут:
https://www.mikesdotnetting.com/article/46/c-regular-expressions-cheat-sheet

Онлайн тестер регулярок: https://regex101.com/

**Comment by Lagodny69** [comment]
Я так понимаю сейчас работает только версия с "я", протестировал. 
Замена ja на я - работает хорошо.
Замена ia на я - работает хорошо. 
Замена на согласный + ja - работает некорректно. Отображается согласный + ъа, а должно согласный + ъя

**Comment by Lagodny69** [comment]
Ещё при тесте заметил такую вещь. 
"Ci" транслитерируется как "Ти". это хорошо
"Сie" как "Те" это хорошо. 
"Cią" как "Тѭ" и так далее тоже хорошо.
"Cia" почему-то как "Ця", а должно быть "Тя".

**Comment by hippogamesunity** [comment]
По поводу твердого знака - достаточно изменить словарь, например
{ "[V]j", "ъ" } заменить на { "[V]ja", "ъя" }. Так ведь? И так для всех переходящих гласных. Иначе никак, компьютер не догадается о таких заменах сам.

По поводу "Cia" - тут сложно, да, сразу 2 буквы изменяются. Относится ли это к этой задаче? Йотированная буква транслируется корректно. Подмешивается вторая проблема, которую предлагаю решать в рамках другой задачи. Требуется сформулировать общее правило, по которому C переходит в T.

**Comment by Lagodny69** [comment]
я тоже так подумал, попробовал сам что-то сделать и написал так:
{ "^Ja", "Я" }, { "^ja", "я" }, { "[C]Ja", "Я" }, { "[C]ja", "я" },
            { "^Ją", "Ѭ" }, { "^ją", "ѭ" }, { "[C]Ją", "Ѭ" }, { "[C]ją", "ѭ" },
            { "^Je", "Е" }, { "^je", "е" }, { "[C]Je", "Е" }, { "[C]je", "е" },
            { "^Ję", "Ѩ" }, { "^ję", "ѩ" }, { "[C]Ję", "Ѩ" }, { "[C]ję", "ѩ" },
            { "^Jo", "Ё" }, { "^jo", "ё" }, { "[C]Jo", "Ё" }, { "[C]jo", "ё" },
            { "^Jó", "É" }, { "^jó", "é" }, { "[C]Jó", "É" }, { "[C]jó", "é" },
            { "^Ju", "Ю" }, { "^ju", "ю" }, { "[C]Ju", "Ю" }, { "[C]ju", "ю" },
            { "^Ji", "Ї" }, { "^ji", "ї" }, { "[C]Ji", "Ї" }, { "[C]ji", "ї" },
            { "[V]Ja", "ъя" }, { "[V]ja", "ъя" },
            { "[V]Ją", "ъѭ" }, { "[V]ją", "ъѭ" },
            { "[V]Je", "ъе" }, { "[V]je", "ъе" },
            { "[V]Ję", "ъѩ" }, { "[V]ję", "ъѩ" },
            { "[V]Jo", "ъё" }, { "[V]jo", "ъё" },
            { "[V]Jó", "ъé" }, { "[V]jó", "ъé" },
            { "[V]Ju", "ъю" }, { "[V]ju", "ъю" },
            { "[V]Ji", "ъї" }, { "[V]ji", "ъї" },
            { "[V]Ia", "я" }, { "[V]ia", "я" },
            { "[V]Ią", "ѭ" }, { "[V]ia", "ѭ" },
            { "[V]Ie", "е" }, { "[V]ia", "е" },
            { "[V]Ię", "ѩ" }, { "[V]ia", "ѩ" },
            { "[V]Io", "ё" }, { "[V]ia", "ё" },
            { "[V]Ió", "é" }, { "[V]ia", "é" },
            { "[V]Iu", "ю" }, { "[V]ia", "ю" },

**Comment by Lagodny69** [comment]
что про "Cia" ну если он делает это как ця возможно потом прото допишем что ця - тя, я так пока вижу. Я имею ввиду транслировать ця в тя

**Comment by Lagodny69** [comment]
тему считаю закрытой
