### ISSUE TITLE
Хитрая Транслитерация 

### ISSUE THREAD

**Issue by Lagodny69** [hippogamesunity/LinguoApp#3]
Есть два хитрый звука которые записываются двумя буквами "rz" и "dź" это "рь" и "дь" соответственно. Мягкие буквы, поэтому когда мы пишем например burza - то это надо записать не как "бурьа", а очевидно "буря" и так далее; dzień - день, odpowiedź - одповедь, porządek - порѩдэк, przypadek - припадэк, dziupło - дюпло.
И ещё одна очень хитрая буква это "l" это мягкое "л", его следует записывать как "ль", поэтому такие слова как w lesie и w lustrze нужно записывать как в лесе и в люстре, а не в лэсе и в лустрьэ.

**Comment by hippogamesunity** [comment]
Сформулируй правило более точно. Как я сейчас это понял:
1. Сделать замену rz>рь
2. По результату провести вторую итерацию замен ьа>я, ье>е

Если это так, то для обоих пунктов нужно указать полный список замен.

**Comment by Lagodny69** [comment]
Ну более точно это превращаться из этого 
Rze
rze
Rzę
rzę
Rza
rza
Rzą
rzą
Rzo
rzo
Rzó
rzó
Rzu
rzu
Rzy
rzy
должны записываться как
Ре
ре
Рѩ
рѩ
Ря
ря
Рѭ
рѭ
Рё
рё
Рé
рé
Рю
рю
Ри
ри
а для dź аналогично
Dzie
dzie
Dzię
dzię
Dzia
dzia
Dzią
dzią
 Dzio
dzio
Dzió
dzió
Dziu
dziu
переходит в 
Де
де
Дѩ
дѩ
Дя
дя
Дѭ
дѭ
Дё
дё
Дé
дé
Дю
дю

**Comment by hippogamesunity** [comment]
Надо выбрать реализацию. Если задачу можно выполнить в рамках простой замены - отлично. Тем более вариантов здесь не так много.
Если требуется реализовать некое правило, то его нужно сформулировать. Например:
Если после rz и dz идет согласная, то транслируем как р и д. Иначе транслируем как рь и дь.
Какой вариант выбираем?

**Comment by Lagodny69** [comment]
Если после rz и dz идёт гласная транслируем как р и д + йотированная гласная. иначе rz и именно dź не dz транслируем как рь и дь

**Comment by Lagodny69** [comment]
Аналогичная ситуация с буквой l если после неё ничего нету или есть согласная, тогда это ль. Если есть гласная, тогда пишется л + йотированная гласная, примеры я подавал выше.

**Comment by hippogamesunity** [comment]
Вижу в задаче 2 проблемы:
- трансляция мягкого знака
- трансляция последующей согласной

Помимо замены rz>р еще происходит замена а>я (и другие). Т.е. есть вторая итерация.
Верно ли правило, что на второй итерации нужно переводить ьа>я? Если да, то нужно составить список всех подобных замен.

**Comment by hippogamesunity** [comment]
Задачу можно закрыть? Если решается обычной заменой

**Comment by Lagodny69** [comment]
можно закрыть
