### ISSUE TITLE
Каноничная транслитерация 

### ISSUE THREAD

**Issue by Lagodny69** [hippogamesunity/LinguoApp#4]
Есть такое понятие как мягкие шипящие. Их просто надо записывать мягко. Что-то аналогичное правилом первого класса жи/ши пиши с буквой и.
[жы/жэ, шы/шэ, щы/щэ, чы/чэ] писаться должны как жи/же, ши/ше, щи/ще, чи/че.
то бишь 
Szczy/szczy Szcze/szcze / Щи/ще Ще/ще
Szy/szy Sze/sze / Ши/ши Ше/ше 
Czy/czy Cze/cze / Чи/чи Че/че
Ży/ży Że/że / Жи/жи Же/же

**Comment by Lagodny69** [comment]
забил в программу так, как придумал на первое время, пока работает

**Comment by hippogamesunity** [comment]
Почему нельзя выполнить эти замены в рамках задачи простой замены? Просто их надо сделать в начале?

**Comment by Lagodny69** [comment]
я так и сделал, тоже об этом подумал

**Comment by hippogamesunity** [comment]
Задачу можно закрыть?

**Comment by Lagodny69** [comment]
можно закрыть
