### ISSUE TITLE
Обратная транслитерация 

### ISSUE THREAD

**Issue by Lagodny69** [hippogamesunity/LinguoApp#5]
Небольшие комментарии к обратной транслитерации:
1. Ь знак (кроме случаев ль нь сь зь рь) должен переводится как ничего 
2. ъ = ' (апостроф приравнивается в твёрдому знаку, значит запись въехать и в'ехать является равноправной и переводится как wjechać)

**Comment by Lagodny69** [comment]
этот вопрос всё ещё актуален

**Comment by hippogamesunity** [comment]
1. сделай трансляцию ль нь сь зь рь, а затем переводи ь>пусто. Будет так работать?
2. транслируй оба символа в пустой символ "", не?

**Comment by Lagodny69** [comment]
хороший план, попробую.

**Comment by Lagodny69** [comment]
мне ещё не до конца понятно как приравнять ъ к '

**Comment by hippogamesunity** [comment]
{ "ъ", "'" } ?

**Comment by Lagodny69** [comment]
в смысле что ' = ъ и дальше он также переводится
въехать и в'ехать должны одинаково транслироваться как wjechać. 
записи с этими знаками равноправные

**Comment by hippogamesunity** [comment]
Я не понимаю. Эти символы пропадают, какая тогда разница что к кому приравнивается?

**Comment by Lagodny69** [comment]
смотри ' используется точно также как и ъ. Это по сути одно и тоже. И когда при трансляции на латиницу они должны одинаково переходить. В принципе то как ты пишешь, одно из решений, то бишь и ' и ъ перевести в ничего. Тогда вопрос: как записать эту трансляцию ' в ничего? Ибо я попытался и у меня ошибка вышла

**Comment by hippogamesunity** [comment]
"должны одинаково переходить". Куда переходить? В пустой символ? Пожалуйста
{ "Ъ", "" }, { "ъ", "" }, { "'", "" },
Залил
въехать и в'ехать = wjechać i wjechać

**Comment by Lagodny69** [comment]
спасибо!

**Comment by Lagodny69** [comment]
Закрыто
