### ISSUE TITLE
Слова исключения 

### ISSUE THREAD

**Issue by Lagodny69** [hippogamesunity/LinguoApp#6]
Как поступить со словами выходящими за правила нашей транслитерации? 
Например слово "вариант" будет переведено по нашим правилам как "warzyant" в то время как это должен быть "wariant". Записывать их в словарь? это решит проблему?

**Comment by hippogamesunity** [comment]
Ну или правила некорректные, или действительно сделать как исключение. Я же не лингвист)

**Comment by Lagodny69** [comment]
исключение ок, их прописать вручную?)))

**Comment by Lagodny69** [comment]
думаю смогу это решать
