### ISSUE TITLE
Дальнейшее развитие проекта

### ISSUE THREAD

**Issue by Lagodny69** [hippogamesunity/LinguoApp#7]
Прошу подробно описать как будет наша работа развиваться дальше и как мы намерены реализовать сайт?

**Comment by hippogamesunity** [comment]
Надо решить, нужна ли тебе мобильная версия проекта (Android/iOS).
Если да, то мы будем использовать Unity, а версия для браузера будет WebGL. Пример WebGL: https://hippogames.itch.io/militaryheroes
Еще надо знать, что WebGL не поддерживается в мобильных браузерах (на телефонах), только на PC. В перспективе, к мобильным приложениям можно будет добавить кастомную клавиатуру.

Если мобильная версия не нужна, и мы делаем только сайт, тогда будет использоваться ASP.NET. Нужно будет зарегаться на Microsoft Azure, убедиться, что там остались бесплатные тарифные планы, ну и сделать сайт. Такой сайт будет работать в любых браузерах, включая мобильные.

**Comment by Lagodny69** [comment]
Я бы уточнить преимущества и недостатки каждого из вариантов, а также их примерные сроки реализации. На данный момент я склоняюсь ко второй версии (кроссплатформенный сайт). Обуславливается это его простой доступностью: 
1. Не нужно ничего скачивать.
2. Доступ с любого устройства.
3. Удобно вносить вправки (они наверняка будут нужны с течением времени)
4. Не занимает место на телефоне.

И вижу пока 1 недостаток это:
Невозможность использовать офлайн.
Возможно ты меня склонишь к первому варианту, но пока как я уже сказал - предпочтительнее выглядит второй. Поделись мнением.

**Comment by hippogamesunity** [comment]
Конечно, второй вариант проще. Но для сайта нужен хостинг, бесплатный полагаю. Его придется поискать. Поиск в гугле "хостинг ASP.NET". Я с этим не работал почти.
Хостинги для WebGL мне хорошо известны, но конечно, этот вариант менее удобный.

**Comment by hippogamesunity** [comment]
Вроде пока пишут бесплатно. Зарегайся тут и пришли мне свои креды.
https://azure.microsoft.com/ru-ru/develop/net/aspnet/

**Comment by Lagodny69** [comment]
Microsoft account is unavailable
Microsoft account is unavailable from this site, so you can't sign in or sign up. The site may be experiencing a problem.

You can sign in or sign up at other Microsoft sites and services, or try again later at this site.

**Comment by Lagodny69** [comment]
-,-

**Comment by Lagodny69** [comment]
можешь ли ты зарегаться?

**Comment by hippogamesunity** [comment]
Я зареган там, но я не смогу дать тебе свою учетку.

**Comment by hippogamesunity** [comment]
try again later at this site

**Comment by Lagodny69** [comment]
ну это я понимаю, но сайт то ты можешь сделать? Или нужно чтобы именно я зарегался?

**Comment by Lagodny69** [comment]
я теоретически могу новую учётку создать

**Comment by hippogamesunity** [comment]
Нашел подходящий хостинг: somee.com/
наш сайт: http://translator.somee.com/
логин/пароль: GeorgeMilovanov/Lagodny69
Как публиковать расскажу по телефону.

**Comment by Lagodny69** [comment]
Считаю тему неактуальной
