### ISSUE TITLE
Мобильная версия 

### ISSUE THREAD

**Issue by Lagodny69** [hippogamesunity/LinguoApp#8]
Нужно найти шаблон отвечающий за мобильную версию, переписать его и добавить ссылки на два других раздела (по аналогии с пк версией, информация и контакты).

**Comment by hippogamesunity** [comment]
Отключил мобильную версию:
https://forums.asp.net/t/2054029.aspx?Disable+Mobile+View+Switcher

**Comment by Lagodny69** [comment]
Думаешь она в принципе не нужна?

**Comment by hippogamesunity** [comment]
Может и нужна, но это нужно быть дизайнером сайтов, чтобы во всем этом шарить.

**Comment by hippogamesunity** [comment]
на телефоне работает, меню есть, все как ты просил)

**Comment by Lagodny69** [comment]
Хахаха ну - задачу ты выполнил, не подкопаться, молодец) Залил это?

**Comment by hippogamesunity** [comment]
да

**Comment by Lagodny69** [comment]
в таком случае тема закрыта
