### ISSUE TITLE
Появились ошибки - нужно фиксить

### ISSUE THREAD

**Issue by Lagodny69** [hippogamesunity/LinguoApp#9]
На сайте не работает раздел информация и связаться. Ошибки HTTP Error 404.0 - Not Found

**Comment by hippogamesunity** [comment]
Вернул мобильную версию и добавил в нее ссылки на разделы. Это файл Site.Mobile.Master.
Если среди знакомых попадутся ребята, которые знают HTML, они помогут сделать все красиво. Тут большим знатоком быть не надо. А при большом желании можешь и сам разобраться, если почитаешь немного про HTML и CSS.

**Comment by Lagodny69** [comment]
Выслал скрин мобильной версии вк

**Comment by Lagodny69** [comment]
хорошо
